### ISSUE TITLE
FaceOSC-Img Link Is Broken

### ISSUE THREAD

**Issue by dderiso** [shiffman/Face-It#9]
Hi Dan, Awesome library! I'm trying to get FaceOSCPuppet to work, but the texture is not displaying as it should, instead it just renders some gray subregion of the Obama image onto the mesh (see image below where I show the strokes so you can see a bit more about the mesh). I think it's because I'm not using FaceOSC-Img, but I can't tell since the dropbox link is no longer valid. Would you consider adding this to the repo? Thanks! -Dave

![screen shot 2015-02-04 at 1 42 53 am](https://cloud.githubusercontent.com/assets/908420/6038108/3023330a-ac0f-11e4-824d-55bfa1a0e0fd.png)

**Comment by dderiso** [comment]
Found the old code, reverted, did some hacking here and there, and it's up. Thanks for the awesome project!

**Comment by kiddmail** [comment]
Hello Dave! I also got this problem, How to solve this problem?
This example is really cool & awesome, I hope I can use that.
Thank you  --Kidd.

**Comment by shiffman** [comment]
Try this! https://www.dropbox.com/s/qm30wbbpul0dec0/FaceOSC-img.zip?dl=0

**Comment by andrejilderda** [comment]
Hi Daniel, I'm afraid the Dropbox link broke again. Can you maybe reupload it? Thanks in advance!

Andre

**Comment by shiffman** [comment]
https://www.dropbox.com/s/wdffoxq3tkq9530/FaceOSC-img.zip?dl=0
